### ISSUE TITLE
I am not able to post data and not even result shows on postman

### ISSUE THREAD

**Issue by NitinSaxenait** [iferc/basic-rocket-web-server#1]
Hi @iferc I am working on the rust api and using your code reference to learn the basics. My get(fetch) is working but the POST is giving an error.
The command I am giving to POST data.
 `curl localhost:8000/todo -X POST -d "Everything is right" -H "Content-Type: application/json"`

The error I am getting:
`
POST /todo application/json:

    => Matched: POST /todo application/json (add_todo_item)

    => Error: Couldn't parse JSON body: Error("expected value", line: 1, column: 1)

    => Outcome: Failure

    => Warning: Responding with 400 Bad Request catcher.

    => Response succeeded.
`
Main code:

```
fn main() {
    {
        let data_connection = match rusqlite::Connection::open("data.sql"){
            Ok(data_connection) => Ok(data_connection
                                          .execute(
                                              "create table if not exists todo_list (
                    id integer primary key,
                    item varchar(64) not null
                );",
                                              rusqlite::NO_PARAMS,
                                          )
                                          .unwrap()),
            Err(error) => Err("Not Connected")
        };

    }
    rocket::ignite().mount("/", routes![fetch_data,add_todo_item]).launch();
}
```
POSTCODE:

```
#[post("/todo", format = "json", data = "<item>")]
fn add_todo_item(item: Json<String>) -> Result<Json<Status>, String> {
    let db_connection = match Connection::open("data.sql") {
        Ok(connection) => connection,
        Err(_) => {
            return Err(String::from("Failed to connect to database"));
        }
    };

    let mut statement =
        match db_connection.prepare("insert into todo_list (id, item) values (null, $1);") {
            Ok(statement) => statement,
            Err(_) => return Err("Failed to prepare query".into()),
        };
    let results = statement.execute(&[&item.0]);

    match results {
        Ok(rows_affected) => Ok(Json(Status {
            message: format!("{} rows inserted!", rows_affected),
        })),
        Err(_) => Err("Failed to insert todo item".into()),
    }
}
```
Can you please help me with this? Thanks!

**Comment by JenChampagne** [comment]
Hi @NitinSaxenait! Sorry for the slow response 🙇‍♀️

The error you're getting is because the endpoint is expecting a JSON string, but you've sent a plain text string instead. For it to qualify as a JSON string, your input needs to be wrapped in double quotes.

Either of these should work for you

```sh
curl localhost:8000/todo -X POST -d "\"Everything is right\"" -H "Content-Type: application/json"
```

```sh
curl localhost:8000/todo -X POST -d '"Everything is right"' -H "Content-Type: application/json"
````

**Comment by iferc** [comment]
Hi @NitinSaxenait! Sorry for the slow response 🙇‍♀️

The error you're getting is because the endpoint is expecting a JSON string, but you've sent a plain text string instead. For it to qualify as a JSON string, your input needs to be wrapped in double quotes.

Either of these should work for you

```sh
curl localhost:8000/todo -X POST -d "\"Everything is right\"" -H "Content-Type: application/json"
```

```sh
curl localhost:8000/todo -X POST -d '"Everything is right"' -H "Content-Type: application/json"
````

Feel free to reopen this or a new issue if you have more questions!
